/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AlertCategory = IDL.Variant({
  'emergency' : IDL.Null,
  'construction' : IDL.Null,
  'event' : IDL.Null,
  'traffic' : IDL.Null,
  'weather' : IDL.Null,
});
export const AlertSeverity = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const CityAlert = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : AlertCategory,
  'severity' : AlertSeverity,
});
export const IncidentStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
});
export const IncidentType = IDL.Variant({
  'accident' : IDL.Null,
  'other' : IDL.Null,
  'fire' : IDL.Null,
  'harassment' : IDL.Null,
  'medical' : IDL.Null,
});
export const IncidentReport = IDL.Record({
  'id' : IDL.Nat,
  'status' : IncidentStatus,
  'latitude' : IDL.Float64,
  'description' : IDL.Text,
  'longitude' : IDL.Float64,
  'timestamp' : Time,
  'reporter' : IDL.Principal,
  'incidentType' : IncidentType,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactType = IDL.Variant({
  'other' : IDL.Null,
  'fire' : IDL.Null,
  'ambulance' : IDL.Null,
  'police' : IDL.Null,
});
export const EmergencyContact = IDL.Record({
  'contactType' : ContactType,
  'name' : IDL.Text,
  'number' : IDL.Text,
});
export const LocationSession = IDL.Record({
  'city' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkInCity' : IDL.Func([IDL.Text], [], []),
  'createCityAlert' : IDL.Func(
      [IDL.Text, IDL.Text, AlertCategory, AlertSeverity],
      [IDL.Nat],
      [],
    ),
  'deactivateAlert' : IDL.Func([IDL.Nat], [], []),
  'getActiveAlerts' : IDL.Func([], [IDL.Vec(CityAlert)], ['query']),
  'getAllAlerts' : IDL.Func([], [IDL.Vec(CityAlert)], ['query']),
  'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmergencyContacts' : IDL.Func([], [IDL.Vec(EmergencyContact)], ['query']),
  'getIncidentsByType' : IDL.Func(
      [IncidentType],
      [IDL.Vec(IncidentReport)],
      ['query'],
    ),
  'getRecentLocationSessions' : IDL.Func(
      [],
      [IDL.Vec(LocationSession)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reportIncident' : IDL.Func(
      [IncidentType, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateIncidentStatus' : IDL.Func([IDL.Nat, IncidentStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AlertCategory = IDL.Variant({
    'emergency' : IDL.Null,
    'construction' : IDL.Null,
    'event' : IDL.Null,
    'traffic' : IDL.Null,
    'weather' : IDL.Null,
  });
  const AlertSeverity = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const CityAlert = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : AlertCategory,
    'severity' : AlertSeverity,
  });
  const IncidentStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
  });
  const IncidentType = IDL.Variant({
    'accident' : IDL.Null,
    'other' : IDL.Null,
    'fire' : IDL.Null,
    'harassment' : IDL.Null,
    'medical' : IDL.Null,
  });
  const IncidentReport = IDL.Record({
    'id' : IDL.Nat,
    'status' : IncidentStatus,
    'latitude' : IDL.Float64,
    'description' : IDL.Text,
    'longitude' : IDL.Float64,
    'timestamp' : Time,
    'reporter' : IDL.Principal,
    'incidentType' : IncidentType,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactType = IDL.Variant({
    'other' : IDL.Null,
    'fire' : IDL.Null,
    'ambulance' : IDL.Null,
    'police' : IDL.Null,
  });
  const EmergencyContact = IDL.Record({
    'contactType' : ContactType,
    'name' : IDL.Text,
    'number' : IDL.Text,
  });
  const LocationSession = IDL.Record({ 'city' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkInCity' : IDL.Func([IDL.Text], [], []),
    'createCityAlert' : IDL.Func(
        [IDL.Text, IDL.Text, AlertCategory, AlertSeverity],
        [IDL.Nat],
        [],
      ),
    'deactivateAlert' : IDL.Func([IDL.Nat], [], []),
    'getActiveAlerts' : IDL.Func([], [IDL.Vec(CityAlert)], ['query']),
    'getAllAlerts' : IDL.Func([], [IDL.Vec(CityAlert)], ['query']),
    'getAllIncidents' : IDL.Func([], [IDL.Vec(IncidentReport)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmergencyContacts' : IDL.Func(
        [],
        [IDL.Vec(EmergencyContact)],
        ['query'],
      ),
    'getIncidentsByType' : IDL.Func(
        [IncidentType],
        [IDL.Vec(IncidentReport)],
        ['query'],
      ),
    'getRecentLocationSessions' : IDL.Func(
        [],
        [IDL.Vec(LocationSession)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reportIncident' : IDL.Func(
        [IncidentType, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateIncidentStatus' : IDL.Func([IDL.Nat, IncidentStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };