/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AlertCategory = { 'emergency' : null } |
  { 'construction' : null } |
  { 'event' : null } |
  { 'traffic' : null } |
  { 'weather' : null };
export type AlertSeverity = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface CityAlert {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'description' : string,
  'timestamp' : Time,
  'category' : AlertCategory,
  'severity' : AlertSeverity,
}
export type ContactType = { 'other' : null } |
  { 'fire' : null } |
  { 'ambulance' : null } |
  { 'police' : null };
export interface EmergencyContact {
  'contactType' : ContactType,
  'name' : string,
  'number' : string,
}
export interface IncidentReport {
  'id' : bigint,
  'status' : IncidentStatus,
  'latitude' : number,
  'description' : string,
  'longitude' : number,
  'timestamp' : Time,
  'reporter' : Principal,
  'incidentType' : IncidentType,
}
export type IncidentStatus = { 'resolved' : null } |
  { 'pending' : null };
export type IncidentType = { 'accident' : null } |
  { 'other' : null } |
  { 'fire' : null } |
  { 'harassment' : null } |
  { 'medical' : null };
export interface LocationSession { 'city' : string, 'timestamp' : Time }
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkInCity' : ActorMethod<[string], undefined>,
  'createCityAlert' : ActorMethod<
    [string, string, AlertCategory, AlertSeverity],
    bigint
  >,
  'deactivateAlert' : ActorMethod<[bigint], undefined>,
  'getActiveAlerts' : ActorMethod<[], Array<CityAlert>>,
  'getAllAlerts' : ActorMethod<[], Array<CityAlert>>,
  'getAllIncidents' : ActorMethod<[], Array<IncidentReport>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmergencyContacts' : ActorMethod<[], Array<EmergencyContact>>,
  'getIncidentsByType' : ActorMethod<[IncidentType], Array<IncidentReport>>,
  'getRecentLocationSessions' : ActorMethod<[], Array<LocationSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reportIncident' : ActorMethod<
    [IncidentType, string, number, number],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateIncidentStatus' : ActorMethod<[bigint, IncidentStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];