/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IncidentReport {
    id: bigint;
    status: IncidentStatus;
    latitude: number;
    description: string;
    longitude: number;
    timestamp: Time;
    reporter: Principal;
    incidentType: IncidentType;
}
export type Time = bigint;
export interface EmergencyContact {
    contactType: ContactType;
    name: string;
    number: string;
}
export interface CityAlert {
    id: bigint;
    title: string;
    active: boolean;
    description: string;
    timestamp: Time;
    category: AlertCategory;
    severity: AlertSeverity;
}
export interface LocationSession {
    city: string;
    timestamp: Time;
}
export interface UserProfile {
    name: string;
}
export enum AlertCategory {
    emergency = "emergency",
    construction = "construction",
    event = "event",
    traffic = "traffic",
    weather = "weather"
}
export enum AlertSeverity {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum ContactType {
    other = "other",
    fire = "fire",
    ambulance = "ambulance",
    police = "police"
}
export enum IncidentStatus {
    resolved = "resolved",
    pending = "pending"
}
export enum IncidentType {
    accident = "accident",
    other = "other",
    fire = "fire",
    harassment = "harassment",
    medical = "medical"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkInCity(city: string): Promise<void>;
    createCityAlert(title: string, description: string, category: AlertCategory, severity: AlertSeverity): Promise<bigint>;
    deactivateAlert(id: bigint): Promise<void>;
    getActiveAlerts(): Promise<Array<CityAlert>>;
    getAllAlerts(): Promise<Array<CityAlert>>;
    getAllIncidents(): Promise<Array<IncidentReport>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmergencyContacts(): Promise<Array<EmergencyContact>>;
    getIncidentsByType(incidentType: IncidentType): Promise<Array<IncidentReport>>;
    getRecentLocationSessions(): Promise<Array<LocationSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    reportIncident(incidentType: IncidentType, description: string, latitude: number, longitude: number): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateIncidentStatus(id: bigint, status: IncidentStatus): Promise<void>;
}
import type { AlertCategory as _AlertCategory, AlertSeverity as _AlertSeverity, CityAlert as _CityAlert, ContactType as _ContactType, EmergencyContact as _EmergencyContact, IncidentReport as _IncidentReport, IncidentStatus as _IncidentStatus, IncidentType as _IncidentType, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkInCity(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInCity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInCity(arg0);
            return result;
        }
    }
    async createCityAlert(arg0: string, arg1: string, arg2: AlertCategory, arg3: AlertSeverity): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCityAlert(arg0, arg1, to_candid_AlertCategory_n3(this._uploadFile, this._downloadFile, arg2), to_candid_AlertSeverity_n5(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCityAlert(arg0, arg1, to_candid_AlertCategory_n3(this._uploadFile, this._downloadFile, arg2), to_candid_AlertSeverity_n5(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async deactivateAlert(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateAlert(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateAlert(arg0);
            return result;
        }
    }
    async getActiveAlerts(): Promise<Array<CityAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAlerts(): Promise<Array<CityAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAlerts();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAlerts();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIncidents(): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIncidents();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIncidents();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmergencyContacts(): Promise<Array<EmergencyContact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmergencyContacts();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmergencyContacts();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIncidentsByType(arg0: IncidentType): Promise<Array<IncidentReport>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIncidentsByType(to_candid_IncidentType_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIncidentsByType(to_candid_IncidentType_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentLocationSessions(): Promise<Array<LocationSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentLocationSessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentLocationSessions();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async reportIncident(arg0: IncidentType, arg1: string, arg2: number, arg3: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.reportIncident(to_candid_IncidentType_n29(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reportIncident(to_candid_IncidentType_n29(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateIncidentStatus(arg0: bigint, arg1: IncidentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIncidentStatus(arg0, to_candid_IncidentStatus_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIncidentStatus(arg0, to_candid_IncidentStatus_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AlertCategory_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertCategory): AlertCategory {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AlertSeverity_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AlertSeverity): AlertSeverity {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CityAlert_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CityAlert): CityAlert {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ContactType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContactType): ContactType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_EmergencyContact_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyContact): EmergencyContact {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentReport_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentReport): IncidentReport {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentStatus): IncidentStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_IncidentType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IncidentType): IncidentType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _IncidentStatus;
    latitude: number;
    description: string;
    longitude: number;
    timestamp: _Time;
    reporter: Principal;
    incidentType: _IncidentType;
}): {
    id: bigint;
    status: IncidentStatus;
    latitude: number;
    description: string;
    longitude: number;
    timestamp: Time;
    reporter: Principal;
    incidentType: IncidentType;
} {
    return {
        id: value.id,
        status: from_candid_IncidentStatus_n17(_uploadFile, _downloadFile, value.status),
        latitude: value.latitude,
        description: value.description,
        longitude: value.longitude,
        timestamp: value.timestamp,
        reporter: value.reporter,
        incidentType: from_candid_IncidentType_n19(_uploadFile, _downloadFile, value.incidentType)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contactType: _ContactType;
    name: string;
    number: string;
}): {
    contactType: ContactType;
    name: string;
    number: string;
} {
    return {
        contactType: from_candid_ContactType_n27(_uploadFile, _downloadFile, value.contactType),
        name: value.name,
        number: value.number
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    active: boolean;
    description: string;
    timestamp: _Time;
    category: _AlertCategory;
    severity: _AlertSeverity;
}): {
    id: bigint;
    title: string;
    active: boolean;
    description: string;
    timestamp: Time;
    category: AlertCategory;
    severity: AlertSeverity;
} {
    return {
        id: value.id,
        title: value.title,
        active: value.active,
        description: value.description,
        timestamp: value.timestamp,
        category: from_candid_AlertCategory_n10(_uploadFile, _downloadFile, value.category),
        severity: from_candid_AlertSeverity_n12(_uploadFile, _downloadFile, value.severity)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    emergency: null;
} | {
    construction: null;
} | {
    event: null;
} | {
    traffic: null;
} | {
    weather: null;
}): AlertCategory {
    return "emergency" in value ? AlertCategory.emergency : "construction" in value ? AlertCategory.construction : "event" in value ? AlertCategory.event : "traffic" in value ? AlertCategory.traffic : "weather" in value ? AlertCategory.weather : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): AlertSeverity {
    return "low" in value ? AlertSeverity.low : "high" in value ? AlertSeverity.high : "medium" in value ? AlertSeverity.medium : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resolved: null;
} | {
    pending: null;
}): IncidentStatus {
    return "resolved" in value ? IncidentStatus.resolved : "pending" in value ? IncidentStatus.pending : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accident: null;
} | {
    other: null;
} | {
    fire: null;
} | {
    harassment: null;
} | {
    medical: null;
}): IncidentType {
    return "accident" in value ? IncidentType.accident : "other" in value ? IncidentType.other : "fire" in value ? IncidentType.fire : "harassment" in value ? IncidentType.harassment : "medical" in value ? IncidentType.medical : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    fire: null;
} | {
    ambulance: null;
} | {
    police: null;
}): ContactType {
    return "other" in value ? ContactType.other : "fire" in value ? ContactType.fire : "ambulance" in value ? ContactType.ambulance : "police" in value ? ContactType.police : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IncidentReport>): Array<IncidentReport> {
    return value.map((x)=>from_candid_IncidentReport_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmergencyContact>): Array<EmergencyContact> {
    return value.map((x)=>from_candid_EmergencyContact_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CityAlert>): Array<CityAlert> {
    return value.map((x)=>from_candid_CityAlert_n8(_uploadFile, _downloadFile, x));
}
function to_candid_AlertCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertCategory): _AlertCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_AlertSeverity_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): _AlertSeverity {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_IncidentStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): _IncidentStatus {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_IncidentType_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentType): _IncidentType {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentType): {
    accident: null;
} | {
    other: null;
} | {
    fire: null;
} | {
    harassment: null;
} | {
    medical: null;
} {
    return value == IncidentType.accident ? {
        accident: null
    } : value == IncidentType.other ? {
        other: null
    } : value == IncidentType.fire ? {
        fire: null
    } : value == IncidentType.harassment ? {
        harassment: null
    } : value == IncidentType.medical ? {
        medical: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IncidentStatus): {
    resolved: null;
} | {
    pending: null;
} {
    return value == IncidentStatus.resolved ? {
        resolved: null
    } : value == IncidentStatus.pending ? {
        pending: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertCategory): {
    emergency: null;
} | {
    construction: null;
} | {
    event: null;
} | {
    traffic: null;
} | {
    weather: null;
} {
    return value == AlertCategory.emergency ? {
        emergency: null
    } : value == AlertCategory.construction ? {
        construction: null
    } : value == AlertCategory.event ? {
        event: null
    } : value == AlertCategory.traffic ? {
        traffic: null
    } : value == AlertCategory.weather ? {
        weather: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AlertSeverity): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == AlertSeverity.low ? {
        low: null
    } : value == AlertSeverity.high ? {
        high: null
    } : value == AlertSeverity.medium ? {
        medium: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
